### ISSUE TITLE
Profiler attachment does not support generic IDocumentStore

### ISSUE THREAD

**Issue by kensykora** [csainty/Glimpse.RavenDb#1]
I've got my code setup such that the config file determines if it setups an embeddable document store or a standard client connection. It'd be really awesome if this project supported both of those, using the generic IDocumentStore type instead of just the Raven.Client.DocumentStore type.

**Comment by csainty** [comment]
Unfortunately it is a limitation of RavenDb that only accepts a full `DocumentStore` class in the profiler. You can see the relevant code here
https://github.com/ravendb/ravendb/blob/master/Raven.Client.MvcIntegration/RavenProfilingHandler.cs#L127

If it would help you, I could accept an `IDocumentStore` but only hook up the profiling if it is `DocumentStore`, similar to how RavenDb itself does it.

**Comment by kensykora** [comment]
Yeah, that is how I ended up working around it too. However, I'm not sure you should accept an IDocumentStore if not all can be handled, as it might be misleading to the developer. Maybe if you threw a NotSupportedException or something along those lines.

Thanks!
